PACKAGE = imcode.server

SOURCE  = \
	ApplicationServer.java \
	DBConnect.java \
	Preference.java \
	InetPoolManager.java \
	LoginUser.java \
	User.java \
	Image.java \
	IMCPoolInterface.java \
	IMCPool.java \
	IMCConstants.java \
	IMCServiceInterface.java \
	IMCService.java \
	ImcServer.java \
	SystemData.java

RMI_SOURCE = IMCPool.java IMCService.java

MAIN       = ImcServer

include $(JAVA_DEV_ROOT)/Makefile
