PACKAGE = imcode.util.log

SOURCE  = \
          LogFormat.java \
          LogLevels.java \
          LogListener.java \
          Log.java \
          LogEvent.java \
          SessionLogger.java \
          SimpleLogFormat.java \
          WriterLogger.java

RMI_SOURCE =

MAIN       =

include $(JAVA_DEV_ROOT)/Makefile

