PACKAGES = \
           . \
           imcode.server \
           imcode.util \
           imcode.util.log \
           imcode.external.diverse

JAVA_DEV_ROOT   = .
INCLUDES	= /usr/local/lib/Opta2000.jar:/usr/local/lib/jakarta-oro-2.0.2-dev-2.jar:/usr/local/lib/servlet.jar:/usr/local/lib/jdbc2_0-stdext.jar

export

include $(JAVA_DEV_ROOT)/make/Makefile
