PACKAGES = \
           . \
           imcode.server \
           imcode.util \
           imcode.util.log \
           imcode.external.diverse

JAVA_DEV_ROOT   = .
INCLUDES	= /usr/local/lib/java/Opta2000.jar:/usr/local/lib/java/jakarta-oro-2.0.2-dev-2.jar:/usr/local/lib/java/jsdk.jar

export
    
include $(JAVA_DEV_ROOT)/make/Makefile
