PACKAGES = \
           . \
           imcode.server \
           imcode.util \
           imcode.util.log \
           imcode.external.diverse

JAVA_DEV_ROOT   = /home/kreiger/imCMS/1.3/server
INCLUDES	= /usr/local/java/Opta2000.jar:/usr/local/java/jakarta-oro-2.0.2-dev-2.jar

export
    
include $(JAVA_DEV_ROOT)/make/Makefile
