DROP PROCEDURE CheckAdminRights

-- 2004-04-27 Kreiger

DROP PROCEDURE GetChilds

-- 2004-05-04 Kreiger

UPDATE users SET login_name=RTRIM(login_name), login_password=RTRIM(login_password),
    first_name=RTRIM(first_name), last_name=RTRIM(last_name), title=RTRIM(title),
    company=RTRIM(company), address=RTRIM(address), city=RTRIM(city),  zip=RTRIM(zip),
    country=RTRIM(country),  county_council=RTRIM(county_council),  email=RTRIM(email)

-- 2004-05-11  Lennart

-- drop tables that we not need anymore.
DROP TABLE main_log
DROP TABLE track_log

-- add Primary Key to table ip_accesses
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.ip_accesses ADD CONSTRAINT
	PK_ip_accesses PRIMARY KEY CLUSTERED
	(
	ip_access_id
	) ON [PRIMARY]

GO
COMMIT

-- add Primary Key to table C_selfreg_roles
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.C_selfreg_roles ADD CONSTRAINT
	PK_C_selfreg_roles PRIMARY KEY CLUSTERED
	(
	selfreg_id
	) ON [PRIMARY]

GO
COMMIT


-- add Primary Key to table C_templates
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.C_templates ADD CONSTRAINT
	PK_C_templates PRIMARY KEY CLUSTERED
	(
	template_id
	) ON [PRIMARY]

GO
COMMIT

-- 2004-06-01 Lennart Å
