///////////////////////////////////////////////////////////
//
//  ChatMember.java
//  Implementation of the Class ChatMember
//  Generated by Enterprise Architect
//  Created on:      2001-07-11
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


public class ChatMember {

	private int userId;
	private String ipNr;
	private int lastChatMsg;
	private String name;

	
	public ChatMember(){

	}

	public String toString(){
		return null;

	}

	public String getName(){
		return null;

	}

	public int getUserId(){
		return 0;

	}

	public String getIPNr(){
		return null;

	}

	public boolean addNewMsg(ChatMsg msg){
		return true;

	}

/*	public Iterator getUnreadMsgs(){

	}*/


}