///////////////////////////////////////////////////////////
//
//  ChatMsg.java
//  Implementation of the Class ChatMsg
//  Generated by Enterprise Architect
//  Created on:      2001-07-11
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////
import java.util.*;

public class ChatMsg {

	private int sender;
	private int msgType;
	private String chatMsg;
	private int reciever;
//	private Date date;

	

	public void ChatMsg(){

	}

	public String toString(){
		return null;

	}

	public int getMsgType(){
		return 0;

	}

	public int getReciever(){
		return 0;

	}

	public int getSender(){
		return 0;

	}


}