///////////////////////////////////////////////////////////
//
//  ChatGroup.java
//  Implementation of the Class ChatGroup
//  Generated by Enterprise Architect
//  Created on:      2001-07-11
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////
import java.util.*;

public class ChatGroup {

	private int groupId;
	private String name;
	private MsgBuffer msgPool;
	private java.util.LinkedList groupMembers;



	public void ChatGroup(){

	}

	public String getChatGroupName(){
		return null;
	

	}

	public int getNrOfGroupMembers(){
		return 0;

	}

/*	public Iterator getAllGroupMembers(){
	Iterator it;
	return it;

	}*/

	public void addNewGroupMember(ChatMember member){

	}

	public boolean removeGroupMember(ChatMember member){
		return true;

	}

	public void addNewMsg(ChatMsg msg){

	}


}