///////////////////////////////////////////////////////////
//
//  MsgBuffer.java
//  Implementation of the Class MsgBuffer
//  Generated by Enterprise Architect
//  Created on:      2001-07-11
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


public class MsgBuffer {

	private java.util.LinkedList msgBuffer;

	

	public void MsgBuffer(){

	}

/*	public iterator getAllMsg(){

	}*/

	public int getNrOfMsg(){
		return 0;

	}

	public void addNewMsg(){

	}


}