module.exports = {
	entry: {
		404: ['imcms-page-error'],
		admin: [
			'imcms-admin_panel',
			'imcms-super-admin',
			'imcms_admin_panel_settings'
		],
		choose_img: [
			'imcms-choose_img',
			'imcms-content_manager',
			'imcms-folder',
			'imcms-folders',
			'imcms-image-metadata'
		],
		document_editor: [
			'imcms-document-editor',
			'imcms-document-editor-head'
		],
		grid: [
			'imcms-grid'
		],
		image_editor: [
			'imcms-advanced-mode',
			'imcms-crop-area',
			'imcms-edit-image',
			'imcms-edit-size',
			'imcms-editable-controls-area',
			'imcms-editable-img',
			'imcms-editable-img-controls',
			'imcms-history-mode',
			'imcms-image-common-info',
			'imcms-image-editor-MEDIA',
			'imcms-image-toolbar',
			'imcms-image_editor',
		],
		import_documents: [
			'imcms-import-documents'
		],
		loop_editor: [
			'imcms-loop_editor',
			'imcms-loop_item',
			'imcms-loop_items',
			'imcms-loop_list',
		],
		menu_editor: [
			'imcms-menu_editor',
			'imcms-menu_item',
			'imcms-menu_items',
			'imcms-menu_list',
		],
		modal_window: [
			'imcms-modal-admin',
			'imcms-modal_window',
		],
		'page-info': [
			'imcms-access_page_info',
			'imcms-all-data_page_info',
			'imcms-appearance_page_info',
			'imcms-cache_page_info',
			'imcms-life-cycle_page_info',
			'imcms-metadata_page_info',
			'imcms-properties_page_info',
			'imcms-status_page_info',
			'imcms-template_page_info',
		],
		'': [
			'imcms-button',
			'imcms-buttons',
			'imcms-calendar',
			'imcms-checkboxes',
			'imcms-choose_image',
			'imcms-control',
			'imcms-controls',
			'imcms-date_picker',
			'imcms-date_time',
			'imcms-edit-user-page',
			'imcms-editor_area',
			'imcms-editor_toolbar',
			'imcms-editor_window',
			'imcms-field',
			'imcms-files_tab_page_info',
			'imcms-flag',
			'imcms-flags',
			'imcms-flex',
			'imcms-fonts',
			'imcms-form',
			'imcms-grid',
			'imcms-head',
			'imcms-imports_files',
			'imcms-info-page',
			'imcms-input',
			'imcms-keyword',
			'imcms-label',
			'imcms-link-button',
			'imcms-loading',
			'imcms-login-page',
			'imcms-logout',
			'imcms-messages',
			'imcms-number_box',
			'imcms-overlays',
			'imcms-placeholder',
			'imcms-pop_up_modal',
			'imcms-radio',
			'imcms-radios',
			'imcms-reset',
			'imcms-scrollbar',
			'imcms-select',
			'imcms-select-document-profile',
			'imcms-select-new-doc-type',
			'imcms-sides',
			'imcms-space-around-inputs',
			'imcms-switch',
			'imcms-switches',
			'imcms-tabs',
			'imcms-text_area',
			'imcms-text_box',
			'imcms-text_editor',
			'imcms-text_history_window',
			'imcms-time_picker',
			'imcms-user-properties',
			'imcms_admin',
		]
	},
	destination: 'dist',
};
