PACKAGE = imcode.util

SOURCE  = \
          GetImages.java \
          MultipartFormdataParser.java \
          MultipartParser.java \
          AdminButtonParser.java \
          FileTagReplacer.java \
          ExStringTokenizer.java \
          Check.java \
          Utility.java \
          IMCServiceRMI.java \
          Prefs.java \
          Parser.java \
          MetaDataParser.java 

RMI_SOURCE = 

MAIN       = 

include $(JAVA_DEV_ROOT)/Makefile
